### ISSUE TITLE
Pip version not up to date

### ISSUE THREAD

**Issue by alexispolti** [AntonKueltz/rfc7539#6]
Hello !

It seems that the version on pip is not up to date with the current repository, preventing it to work with Python 3.10. Coud you update it please?
Thanx a lot! :-)

**Comment by AntonKueltz** [comment]
Yep, forgot to add the updates to pypi, sorry about that. New release can be found here - https://pypi.org/project/rfc7539/2.1.0/

**Comment by alexispolti** [comment]
Thanx a lot :-)
